load(":tilt.bzl", "tilt_down", "tilt_up")

# Bring up the full set of services for development
tilt_up(
    name = "up",
)

# Bring down any remaining/running services
tilt_down(
    name = "down",
)

python_bootstrap_binary(
    name = "healthcheck",
    main = "healthcheck.py",
    visibility = ["PUBLIC"],
)

load("@toolchains//rover:macros.bzl", "supergraph", "diff_check", "dev_update_file")

supergraph(
  name = "supergraph",
  config = "apollo/supergraph-config.yaml",
  subgraphs = {
    "API_SCHEMA": "//core/api:sdl",
  },
  rover_bin = "//third-party/rover:rover"
)

dev_update_file(
  name = "update-supergraph",
  generated = ":supergraph",
  out = "apollo/supergraph.graphql"
)

diff_check(
  name = "supergraph-diff",
  original = "apollo/supergraph.graphql",
  new = ":supergraph"
)

sh_binary(
  name = "update-schemas",
  main = "bin/update-schemas.sh",
)

test_suite(
    name = "check-sdls",
    tests = [
        ":supergraph-diff",
        "//core/api:schema-diff",
    ],
)
