---
version: "3"
services:
  oathkeeper:
    image: oryd/oathkeeper:v0.40.4-distroless
    command: serve -c /home/ory/oathkeeper.yml --sqa-opt-out
    ports:
      - 4002:4455
      - 4456:4456 #! Internal
    extra_hosts:
      - fundcatchup-host:host-gateway
    volumes:
      - ./ory:/home/ory

  kratos:
    image: oryd/kratos:latest #! This image was created locally from kratos @master:0e45e87632b1982f51200b6ef167870646051488
    extra_hosts:
      - fundcatchup-host:host-gateway
    ports:
      - "4433:4433" #! public
      - "4434:4434" #! admin
    command: serve -c /home/ory/kratos.yml --watch-courier --sqa-opt-out
    environment:
      DSN: postgres://user:password@kratos-pg:5432/kratos?sslmode=disable
    links:
      - kratos-pg:kratos-pg
      - mailslurper:mailslurper
    depends_on:
      - kratos-migrate
    volumes:
      - ./ory:/home/ory
  kratos-migrate:
    image: oryd/kratos:latest
    command: -c /home/ory/kratos.yml migrate sql -y -e
    environment:
      DSN: postgres://user:password@kratos-pg:5432/kratos?sslmode=disable
    links:
      - kratos-pg:kratos-pg
    volumes:
      - ./ory:/home/ory
  kratos-pg:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kratos
  mailslurper:
    image: oryd/mailslurper:latest-smtps

  apollo-router:
    image: ghcr.io/apollographql/router:v1.25.0
    ports:
      - 4004:4004
    extra_hosts:
      - fundcatchup-host:host-gateway
    environment:
      - APOLLO_ROUTER_SUPERGRAPH_PATH=/dev/apollo/supergraph.graphql
      - APOLLO_ROUTER_CONFIG_PATH=/dev/apollo/router.yaml
    volumes:
      - ./apollo:/dev/apollo

  otel-agent:
    ports:
      - "4318:4318" #! http receiver
      - "4317:4317" #! grpc receiver
    image: otel/opentelemetry-collector-contrib:0.84.0
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    volumes:
      - ./otel-agent.yml:/etc/otel-agent-config.yaml

  api-pg:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    ports:
      - 5433:5432
