---
version: "3"
services:
  oathkeeper:
    image: oryd/oathkeeper:v0.40.4-distroless
    command: serve -c /home/ory/oathkeeper.yml --sqa-opt-out
    ports:
      - 4002:4455
    extra_hosts:
      - fundcatchup-host:host-gateway
    volumes:
      - ./ory:/home/ory

  kratos:
    image: oryd/kratos:v1.0.0
    extra_hosts:
      - fundcatchup-host:host-gateway
    ports:
      - "4433:4433" #! public
      - "4434:4434" #! admin
    entrypoint: sh -c
    command: '"kratos migrate sql up -y -e && kratos serve -c /home/ory/kratos.yml --watch-courier --sqa-opt-out"'
    environment:
      DSN: postgres://user:password@kratos-pg:5432/kratos?sslmode=disable
    links:
      - kratos-pg:kratos-pg
      - mailslurper:mailslurper
    volumes:
      - ./ory:/home/ory
  kratos-pg:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kratos
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"

  apollo-router:
    image: ghcr.io/apollographql/router:v1.25.0
    ports:
      - 4004:4004
    extra_hosts:
      - fundcatchup-host:host-gateway
    environment:
      - APOLLO_ROUTER_SUPERGRAPH_PATH=/dev/apollo/supergraph.graphql
      - APOLLO_ROUTER_CONFIG_PATH=/dev/apollo/router.yaml
    volumes:
      - ./apollo:/dev/apollo

  otel-agent:
    ports:
      - "4318:4318" #! http receiver
      - "4317:4317" #! grpc receiver
    image: otel/opentelemetry-collector-contrib:0.84.0
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    volumes:
      - ./otel-agent.yml:/etc/otel-agent-config.yaml

  api-pg:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    ports:
      - 5433:5432
