name: "Bats test"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Bats tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Buck2 build
        run: nix develop -c buck2 build //core/api
      - name: Run bats tests
        run: |
          nix develop -c bats --setup-suite-file e2e/setup_suite.bash -t e2e/core/**
